# config/packages/mailer.yaml
framework:
    mailer:
#        dsn: '%env(MAILER_DSN)%'
        transports:
            main: '%env(MAILER_URL)%'
 #           alternative: '%env(MAILER_DSN_IMPORTANT)%'
#
