twig:
    globals:  { 
        app_name: 'SERO-EPHI', 
        app_description: 'Scientific and Ethical Review Office Online', 
        organization: null, 
        app_url: ntc.ephi.gov.et, 
        app_email: sero@ephi.gov.et,
        site_logo: ephi.png, 
        copyright: 'SNTC -EPHI', 
        navbar_background: dark, 
        acronym: 'SERO', 
        corporate_color: '#54b4', 
        profile_pictures: 'uploads/files/profile_pictures',
        motto: 'Motto',  
        site_setting: '%kernel.project_dir%/uploads/files/site_setting/ephi.png',
        contact_us: 'SNTC -EPHI', 
        about: 'SNTC -EPHI',
        privacy_statement: 'SNTC -EPHI' 
        }